// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2iBzk3t45af40H1uH8L7rAdc3cy5yOHI',
    appId: '1:597098679627:web:f2a203f5a2d68f3416ecce',
    messagingSenderId: '597098679627',
    projectId: 'firee-91a9d',
    authDomain: 'firee-91a9d.firebaseapp.com',
    storageBucket: 'firee-91a9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4n8n5--c5o_EzA3YPdVcQ3R-hKMR-B4',
    appId: '1:597098679627:android:88a282e55396278216ecce',
    messagingSenderId: '597098679627',
    projectId: 'firee-91a9d',
    storageBucket: 'firee-91a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlQ40ZHInReojJP4C2ql8ZW5yecuJJAM',
    appId: '1:597098679627:ios:7cadef821de671af16ecce',
    messagingSenderId: '597098679627',
    projectId: 'firee-91a9d',
    storageBucket: 'firee-91a9d.appspot.com',
    iosBundleId: 'com.example.demo',
  );
}
